### ISSUE TITLE
Help files and Deken search

### ISSUE THREAD

**Issue by 60-hz** [agraef/pd-lua#11]
Great external.

I suggest to add [declare -lib pdlua] & [declare -path examples] objets In pdlua-help.pd and other help files so everything load correctly.

Also I would love to be able to see this external in Deken for some class (right now I can see only an old extended version from 2015).

Cheers!

**Comment by porres** [comment]
I just sent a PR for this and will try to offer these as part of ELSE properly in deken, see https://github.com/agraef/pd-lua/pull/12
