### ISSUE TITLE
request, ship the html tutorial and its examples

### ISSUE THREAD

**Issue by porres** [agraef/pd-lua#18]
I realized you don't have the tutorial examples in the release download. Maybe it's worth shipping them.

By the way, we could maybe wrap up a new release just to offer these recent documentation updates and the plugdata support.

**Comment by agraef** [comment]
Yes, I can see how you incorporated these in ELSE, seems reasonable to me. But I guess that I should first switch to pd-lib-builder (#5).

There's also a couple of other (older) issues that I need to look into, before I can do the next release. Currently busy with other things. :(

**Comment by agraef** [comment]
Ok, this should now be fixed with rev. 406a2aad1b2a94bf139097c7c0eacbe68f9e72da (pending release).
