### ISSUE TITLE
upgrade build system to pd-lib-builder

### ISSUE THREAD

**Issue by claudeha** [agraef/pd-lua#5]
pd-lib-builder is a Makefile that is used by many external libraries.

<https://github.com/pure-data/pd-lib-builder>

Much easier to merge improvements from upstream than the old Makefile template (which afaict is no longer maintained).  In particular the subtree method: <https://github.com/pure-data/pd-lib-builder/blob/master/tips-tricks.md#git-subtree>

**Comment by claudeha** [comment]
Maybe better to wait until it supports Android (afaict the old Makefile template does, and the new pd-lib-builder does not).

**Comment by agraef** [comment]
Yep, I've been thinking about this lately as well. Should be easy to do. Maybe while we're at it we should also adopt the way compilation works downstream in plugdata and ELSE which was devised by Tim Schoen over at the plugdata project. It includes Lua as a submodule and just adds onelua.c to the compile sources. No more external dependencies (apart from Pd for the m_pd.h header file, that is).
