### ISSUE TITLE
support double-precision Pd

### ISSUE THREAD

**Issue by claudeha** [agraef/pd-lua#6]
The next release of Pd will support compiling in double-precision mode.  All externals must also be compiled to support it.  Apparently pdlua single-precision crashes in double-precision Pd, probably because of a null class pointer?

<https://lists.puredata.info/pipermail/pd-dev/2020-03/022322.html>

Though, this is testing with an unspecified version copy/pasted from ancient Pd-extended...

If possible, compile a "fat" binary that will "just work" in both single-precision and double-precision Pd.

**Comment by claudeha** [comment]
https://github.com/claudeha/pd-lua/tree/issue-6-double-precision-fat-binary is some hackery to get fat binary working with the current state of Pd.  Hopefully Pd upstream will see how horrible this is and rethink how they do it...

**Comment by agraef** [comment]
Sorry, somehow I missed these. The branch has merge conflicts now, so I will have to see how I can get these sorted out.

**Comment by agraef** [comment]
This whole "flat" (float/double) binary concept is just too convoluted for my taste. I'd rather leave it to the Deken package maintainers (which I'm not) to get this sorted out in some way.

Concerning the binaries that I release here, I'll just keep building packages for the current vanilla version. If vanilla actually switches to double, then I'll just recompile the package and be done with it.

https://github.com/agraef/pd-lua/commit/eaf7c472a15972692931d23f9a9393d9804a6a47 seems reasonable, though, a bit of defensive programming can't hurt. And it should merge cleanly.

**Comment by agraef** [comment]
Merged in rev. d9a1df45d7dd8c07e52bd8600b7403bf0dbc934f, thanks!
